apiVersion: v1
kind: ServiceAccount
metadata:
  name: sre-agent-sa
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sre-agent-role
rules:
- apiGroups: [""] # Core API group
  resources: ["pods", "pods/log", "events"]
  verbs: ["get", "list", "watch"] # Required for detection and analysis
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["delete"] # Required for self-healing action (if enabled)

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sre-agent-binding
subjects:
- kind: ServiceAccount
  name: sre-agent-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: sre-agent-role
  apiGroup: rbac.authorization.k8s.io
